//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodesysIIS
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData' 的 XML 註解
    public partial class DrillData
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData' 的 XML 註解
    {
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData.CompanyName' 的 XML 註解
        public string CompanyName { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData.CompanyName' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData.Dia' 的 XML 註解
        public double Dia { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData.Dia' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData.RunSeconds' 的 XML 註解
        public double RunSeconds { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData.RunSeconds' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData.FeedQuantity' 的 XML 註解
        public double FeedQuantity { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData.FeedQuantity' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData.Rpm' 的 XML 註解
        public double Rpm { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData.Rpm' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData.Speed' 的 XML 註解
        public double Speed { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData.Speed' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData.WriteDate' 的 XML 註解
        public System.DateTime WriteDate { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData.WriteDate' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'DrillData.ID' 的 XML 註解
        public int ID { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'DrillData.ID' 的 XML 註解
    }
}
