//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodesysIIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities' 的 XML 註解
    public partial class MecEntities : DbContext
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities' 的 XML 註解
    {
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.MecEntities()' 的 XML 註解
        public MecEntities()
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.MecEntities()' 的 XML 註解
            : base("name=MecEntities")
        {
        }
    
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.OnModelCreating(DbModelBuilder)' 的 XML 註解
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.OnModelCreating(DbModelBuilder)' 的 XML 註解
        {
            throw new UnintentionalCodeFirstException();
        }
    
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.BuildErrorCode' 的 XML 註解
        public virtual DbSet<BuildErrorCode> BuildErrorCode { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.BuildErrorCode' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.DrillData' 的 XML 註解
        public virtual DbSet<DrillData> DrillData { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.DrillData' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.MSAxisMain' 的 XML 註解
        public virtual DbSet<MSAxisMain> MSAxisMain { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.MSAxisMain' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.MSRuler' 的 XML 註解
        public virtual DbSet<MSRuler> MSRuler { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.MSRuler' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.MSServoAxis' 的 XML 註解
        public virtual DbSet<MSServoAxis> MSServoAxis { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.MSServoAxis' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.ThrowErrorCode' 的 XML 註解
        public virtual DbSet<ThrowErrorCode> ThrowErrorCode { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.ThrowErrorCode' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MecEntities.MSIO' 的 XML 註解
        public virtual DbSet<MSIO> MSIO { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MecEntities.MSIO' 的 XML 註解
    }
}
