//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodesysIIS
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MSAxisMain' 的 XML 註解
    public partial class MSAxisMain
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MSAxisMain' 的 XML 註解
    {
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.CompanyName' 的 XML 註解
        public string CompanyName { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.CompanyName' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.Electric' 的 XML 註解
        public float Electric { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.Electric' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.Position' 的 XML 註解
        public string Position { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.Position' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.Speed' 的 XML 註解
        public float Speed { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.Speed' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.FeedQuantity' 的 XML 註解
        public float FeedQuantity { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.FeedQuantity' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.WriteDate' 的 XML 註解
        public System.DateTime WriteDate { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.WriteDate' 的 XML 註解
#pragma warning disable CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.ID' 的 XML 註解
        public int ID { get; set; }
#pragma warning restore CS1591 // 遺漏公用可見類型或成員 'MSAxisMain.ID' 的 XML 註解
    }
}
