//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPG.Memor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Codesys.Memor", ConfigurationName="Memor.IMemor")]
    public interface IMemor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.Memor/IMemor/Create", ReplyAction="http://Codesys.Memor/IMemor/CreateResponse")]
        GD_STD.Host Create(GD_STD.Host host, string company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.Memor/IMemor/Create", ReplyAction="http://Codesys.Memor/IMemor/CreateResponse")]
        System.Threading.Tasks.Task<GD_STD.Host> CreateAsync(GD_STD.Host host, string company);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemorChannel : MPG.Memor.IMemor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemorClient : System.ServiceModel.ClientBase<MPG.Memor.IMemor>, MPG.Memor.IMemor {
        
        public MemorClient() {
        }
        
        public MemorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GD_STD.Host Create(GD_STD.Host host, string company) {
            return base.Channel.Create(host, company);
        }
        
        public System.Threading.Tasks.Task<GD_STD.Host> CreateAsync(GD_STD.Host host, string company) {
            return base.Channel.CreateAsync(host, company);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Codesys.WriteMemor", ConfigurationName="Memor.IWriteMemor")]
    public interface IWriteMemor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetPanel", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetPanelResponse")]
        void SetPanel(GD_STD.PanelButton value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetPanel", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetPanelResponse")]
        System.Threading.Tasks.Task SetPanelAsync(GD_STD.PanelButton value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetDrillWarehouse", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetDrillWarehouseResponse")]
        void SetDrillWarehouse(GD_STD.DrillWarehouse value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetDrillWarehouse", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetDrillWarehouseResponse")]
        System.Threading.Tasks.Task SetDrillWarehouseAsync(GD_STD.DrillWarehouse value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetOill", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetOillResponse")]
        void SetOill(GD_STD.OillSystem value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetOill", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetOillResponse")]
        System.Threading.Tasks.Task SetOillAsync(GD_STD.OillSystem value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetHydraulic", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetHydraulicResponse")]
        void SetHydraulic(GD_STD.OillSystem value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetHydraulic", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetHydraulicResponse")]
        System.Threading.Tasks.Task SetHydraulicAsync(GD_STD.OillSystem value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetLubricant", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetLubricantResponse")]
        void SetLubricant(GD_STD.OillSystem value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetLubricant", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetLubricantResponse")]
        System.Threading.Tasks.Task SetLubricantAsync(GD_STD.OillSystem value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetCut", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetCutResponse")]
        void SetCut(GD_STD.OillSystem value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetCut", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetCutResponse")]
        System.Threading.Tasks.Task SetCutAsync(GD_STD.OillSystem value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetHost", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetHostResponse")]
        void SetHost(GD_STD.Host value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetHost", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetHostResponse")]
        System.Threading.Tasks.Task SetHostAsync(GD_STD.Host value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetProcessingInfo", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetProcessingInfoResponse")]
        void SetProcessingInfo(GD_STD.ProcessingInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetProcessingInfo", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetProcessingInfoResponse")]
        System.Threading.Tasks.Task SetProcessingInfoAsync(GD_STD.ProcessingInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetOutage", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetOutageResponse")]
        void SetOutage(GD_STD.Outage value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetOutage", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetOutageResponse")]
        System.Threading.Tasks.Task SetOutageAsync(GD_STD.Outage value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetMPG", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetMPGResponse")]
        void SetMPG(GD_STD.MPG value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.WriteMemor/IWriteMemor/SetMPG", ReplyAction="http://Codesys.WriteMemor/IWriteMemor/SetMPGResponse")]
        System.Threading.Tasks.Task SetMPGAsync(GD_STD.MPG value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWriteMemorChannel : MPG.Memor.IWriteMemor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WriteMemorClient : System.ServiceModel.ClientBase<MPG.Memor.IWriteMemor>, MPG.Memor.IWriteMemor {
        
        public WriteMemorClient() {
        }
        
        public WriteMemorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WriteMemorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WriteMemorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WriteMemorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetPanel(GD_STD.PanelButton value) {
            base.Channel.SetPanel(value);
        }
        
        public System.Threading.Tasks.Task SetPanelAsync(GD_STD.PanelButton value) {
            return base.Channel.SetPanelAsync(value);
        }
        
        public void SetDrillWarehouse(GD_STD.DrillWarehouse value) {
            base.Channel.SetDrillWarehouse(value);
        }
        
        public System.Threading.Tasks.Task SetDrillWarehouseAsync(GD_STD.DrillWarehouse value) {
            return base.Channel.SetDrillWarehouseAsync(value);
        }
        
        public void SetOill(GD_STD.OillSystem value) {
            base.Channel.SetOill(value);
        }
        
        public System.Threading.Tasks.Task SetOillAsync(GD_STD.OillSystem value) {
            return base.Channel.SetOillAsync(value);
        }
        
        public void SetHydraulic(GD_STD.OillSystem value) {
            base.Channel.SetHydraulic(value);
        }
        
        public System.Threading.Tasks.Task SetHydraulicAsync(GD_STD.OillSystem value) {
            return base.Channel.SetHydraulicAsync(value);
        }
        
        public void SetLubricant(GD_STD.OillSystem value) {
            base.Channel.SetLubricant(value);
        }
        
        public System.Threading.Tasks.Task SetLubricantAsync(GD_STD.OillSystem value) {
            return base.Channel.SetLubricantAsync(value);
        }
        
        public void SetCut(GD_STD.OillSystem value) {
            base.Channel.SetCut(value);
        }
        
        public System.Threading.Tasks.Task SetCutAsync(GD_STD.OillSystem value) {
            return base.Channel.SetCutAsync(value);
        }
        
        public void SetHost(GD_STD.Host value) {
            base.Channel.SetHost(value);
        }
        
        public System.Threading.Tasks.Task SetHostAsync(GD_STD.Host value) {
            return base.Channel.SetHostAsync(value);
        }
        
        public void SetProcessingInfo(GD_STD.ProcessingInfo value) {
            base.Channel.SetProcessingInfo(value);
        }
        
        public System.Threading.Tasks.Task SetProcessingInfoAsync(GD_STD.ProcessingInfo value) {
            return base.Channel.SetProcessingInfoAsync(value);
        }
        
        public void SetOutage(GD_STD.Outage value) {
            base.Channel.SetOutage(value);
        }
        
        public System.Threading.Tasks.Task SetOutageAsync(GD_STD.Outage value) {
            return base.Channel.SetOutageAsync(value);
        }
        
        public void SetMPG(GD_STD.MPG value) {
            base.Channel.SetMPG(value);
        }
        
        public System.Threading.Tasks.Task SetMPGAsync(GD_STD.MPG value) {
            return base.Channel.SetMPGAsync(value);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Codesys.ReadMemor", ConfigurationName="Memor.IReadMemor")]
    public interface IReadMemor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetPanel", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetPanelResponse")]
        GD_STD.PanelButton GetPanel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetPanel", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetPanelResponse")]
        System.Threading.Tasks.Task<GD_STD.PanelButton> GetPanelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetDrillWarehouse", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetDrillWarehouseResponse")]
        GD_STD.DrillWarehouse GetDrillWarehouse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetDrillWarehouse", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetDrillWarehouseResponse")]
        System.Threading.Tasks.Task<GD_STD.DrillWarehouse> GetDrillWarehouseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetOill", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetOillResponse")]
        GD_STD.OillSystem GetOill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetOill", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetOillResponse")]
        System.Threading.Tasks.Task<GD_STD.OillSystem> GetOillAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetHydraulic", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetHydraulicResponse")]
        GD_STD.HydraulicSystem[] GetHydraulic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetHydraulic", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetHydraulicResponse")]
        System.Threading.Tasks.Task<GD_STD.HydraulicSystem[]> GetHydraulicAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetLubricant", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetLubricantResponse")]
        GD_STD.LubricantSystem GetLubricant();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetLubricant", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetLubricantResponse")]
        System.Threading.Tasks.Task<GD_STD.LubricantSystem> GetLubricantAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetCut", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetCutResponse")]
        GD_STD.CutOilSystem GetCut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetCut", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetCutResponse")]
        System.Threading.Tasks.Task<GD_STD.CutOilSystem> GetCutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetInput", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetInputResponse")]
        GD_STD.Input GetInput();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetInput", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetInputResponse")]
        System.Threading.Tasks.Task<GD_STD.Input> GetInputAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetOutput", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetOutputResponse")]
        GD_STD.Output GetOutput();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetOutput", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetOutputResponse")]
        System.Threading.Tasks.Task<GD_STD.Output> GetOutputAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetAxisInfo", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetAxisInfoResponse")]
        GD_STD.AxisInfo GetAxisInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetAxisInfo", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetAxisInfoResponse")]
        System.Threading.Tasks.Task<GD_STD.AxisInfo> GetAxisInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetHost", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetHostResponse")]
        GD_STD.Host GetHost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetHost", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetHostResponse")]
        System.Threading.Tasks.Task<GD_STD.Host> GetHostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetProcessingInfo", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetProcessingInfoResponse")]
        GD_STD.ProcessingInfo GetProcessingInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetProcessingInfo", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetProcessingInfoResponse")]
        System.Threading.Tasks.Task<GD_STD.ProcessingInfo> GetProcessingInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetOutage", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetOutageResponse")]
        GD_STD.Outage GetOutage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Codesys.ReadMemor/IReadMemor/GetOutage", ReplyAction="http://Codesys.ReadMemor/IReadMemor/GetOutageResponse")]
        System.Threading.Tasks.Task<GD_STD.Outage> GetOutageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReadMemorChannel : MPG.Memor.IReadMemor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadMemorClient : System.ServiceModel.ClientBase<MPG.Memor.IReadMemor>, MPG.Memor.IReadMemor {
        
        public ReadMemorClient() {
        }
        
        public ReadMemorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReadMemorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReadMemorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReadMemorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GD_STD.PanelButton GetPanel() {
            return base.Channel.GetPanel();
        }
        
        public System.Threading.Tasks.Task<GD_STD.PanelButton> GetPanelAsync() {
            return base.Channel.GetPanelAsync();
        }
        
        public GD_STD.DrillWarehouse GetDrillWarehouse() {
            return base.Channel.GetDrillWarehouse();
        }
        
        public System.Threading.Tasks.Task<GD_STD.DrillWarehouse> GetDrillWarehouseAsync() {
            return base.Channel.GetDrillWarehouseAsync();
        }
        
        public GD_STD.OillSystem GetOill() {
            return base.Channel.GetOill();
        }
        
        public System.Threading.Tasks.Task<GD_STD.OillSystem> GetOillAsync() {
            return base.Channel.GetOillAsync();
        }
        
        public GD_STD.HydraulicSystem[] GetHydraulic() {
            return base.Channel.GetHydraulic();
        }
        
        public System.Threading.Tasks.Task<GD_STD.HydraulicSystem[]> GetHydraulicAsync() {
            return base.Channel.GetHydraulicAsync();
        }
        
        public GD_STD.LubricantSystem GetLubricant() {
            return base.Channel.GetLubricant();
        }
        
        public System.Threading.Tasks.Task<GD_STD.LubricantSystem> GetLubricantAsync() {
            return base.Channel.GetLubricantAsync();
        }
        
        public GD_STD.CutOilSystem GetCut() {
            return base.Channel.GetCut();
        }
        
        public System.Threading.Tasks.Task<GD_STD.CutOilSystem> GetCutAsync() {
            return base.Channel.GetCutAsync();
        }
        
        public GD_STD.Input GetInput() {
            return base.Channel.GetInput();
        }
        
        public System.Threading.Tasks.Task<GD_STD.Input> GetInputAsync() {
            return base.Channel.GetInputAsync();
        }
        
        public GD_STD.Output GetOutput() {
            return base.Channel.GetOutput();
        }
        
        public System.Threading.Tasks.Task<GD_STD.Output> GetOutputAsync() {
            return base.Channel.GetOutputAsync();
        }
        
        public GD_STD.AxisInfo GetAxisInfo() {
            return base.Channel.GetAxisInfo();
        }
        
        public System.Threading.Tasks.Task<GD_STD.AxisInfo> GetAxisInfoAsync() {
            return base.Channel.GetAxisInfoAsync();
        }
        
        public GD_STD.Host GetHost() {
            return base.Channel.GetHost();
        }
        
        public System.Threading.Tasks.Task<GD_STD.Host> GetHostAsync() {
            return base.Channel.GetHostAsync();
        }
        
        public GD_STD.ProcessingInfo GetProcessingInfo() {
            return base.Channel.GetProcessingInfo();
        }
        
        public System.Threading.Tasks.Task<GD_STD.ProcessingInfo> GetProcessingInfoAsync() {
            return base.Channel.GetProcessingInfoAsync();
        }
        
        public GD_STD.Outage GetOutage() {
            return base.Channel.GetOutage();
        }
        
        public System.Threading.Tasks.Task<GD_STD.Outage> GetOutageAsync() {
            return base.Channel.GetOutageAsync();
        }
    }
}
