//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSTD105 {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelPath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelPath() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFSTD105.ModelPath", typeof(ModelPath).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 MecSetting 的當地語系化字串。
        /// </summary>
        public static string BackupMecSetting {
            get {
                return ResourceManager.GetString("BackupMecSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OptionSettings 的當地語系化字串。
        /// </summary>
        public static string BackupOptionSettings {
            get {
                return ResourceManager.GetString("BackupOptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TeklaBom.csv 的當地語系化字串。
        /// </summary>
        public static string Bom {
            get {
                return ResourceManager.GetString("Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ParameterSetting 的當地語系化字串。
        /// </summary>
        public static string DefaultParameterSetting {
            get {
                return ResourceManager.GetString("DefaultParameterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dev_Part 的當地語系化字串。
        /// </summary>
        public static string Dev_Part {
            get {
                return ResourceManager.GetString("Dev_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dev_Material 的當地語系化字串。
        /// </summary>
        public static string DevMaterial {
            get {
                return ResourceManager.GetString("DevMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DrillBoltsEdited 的當地語系化字串。
        /// </summary>
        public static string DrillBoltsBackup {
            get {
                return ResourceManager.GetString("DrillBoltsBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DrillBrand.lis 的當地語系化字串。
        /// </summary>
        public static string DrillBrand {
            get {
                return ResourceManager.GetString("DrillBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DW.db 的當地語系化字串。
        /// </summary>
        public static string DrillWarehouse {
            get {
                return ResourceManager.GetString("DrillWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mater.lis 的當地語系化字串。
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MDV.lis 的當地語系化字串。
        /// </summary>
        public static string MaterialDataView {
            get {
                return ResourceManager.GetString("MaterialDataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MecSetting.db 的當地語系化字串。
        /// </summary>
        public static string MecSetting {
            get {
                return ResourceManager.GetString("MecSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DSTV_Profile 的當地語系化字串。
        /// </summary>
        public static string Nc {
            get {
                return ResourceManager.GetString("Nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Nc.tp 的當地語系化字串。
        /// </summary>
        public static string NcBackup {
            get {
                return ResourceManager.GetString("NcBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OptionSettings.db 的當地語系化字串。
        /// </summary>
        public static string OptionSettings {
            get {
                return ResourceManager.GetString("OptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Profile 的當地語系化字串。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProfileList.lis 的當地語系化字串。
        /// </summary>
        public static string ProfileList {
            get {
                return ResourceManager.GetString("ProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProjectInfo.db 的當地語系化字串。
        /// </summary>
        public static string ProjectProperty {
            get {
                return ResourceManager.GetString("ProjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ReportLogo 的當地語系化字串。
        /// </summary>
        public static string ReportLogo {
            get {
                return ResourceManager.GetString("ReportLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SteelAssembly.lis 的當地語系化字串。
        /// </summary>
        public static string SteelAssembly {
            get {
                return ResourceManager.GetString("SteelAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SteelBolts 的當地語系化字串。
        /// </summary>
        public static string SteelBolts {
            get {
                return ResourceManager.GetString("SteelBolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SteelPart 的當地語系化字串。
        /// </summary>
        public static string SteelPart {
            get {
                return ResourceManager.GetString("SteelPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMB 的當地語系化字串。
        /// </summary>
        public static string WorkMaterialBackup {
            get {
                return ResourceManager.GetString("WorkMaterialBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkMaterialIndexBackup.back 的當地語系化字串。
        /// </summary>
        public static string WorkMaterialIndexBackup {
            get {
                return ResourceManager.GetString("WorkMaterialIndexBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkMaterialOtherBackup.back 的當地語系化字串。
        /// </summary>
        public static string WorkMaterialOtherBackup {
            get {
                return ResourceManager.GetString("WorkMaterialOtherBackup", resourceCulture);
            }
        }
    }
}
