//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD_STD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    public sealed partial class Optional : global::System.Configuration.ApplicationSettingsBase {
        
        private static Optional defaultInstance = ((Optional)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Optional())));
        
        public static Optional Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Middle {
            get {
                return ((bool)(this["Middle"]));
            }
            set {
                this["Middle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeftExport {
            get {
                return ((bool)(this["LeftExport"]));
            }
            set {
                this["LeftExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RightExport {
            get {
                return ((bool)(this["RightExport"]));
            }
            set {
                this["RightExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeftEntrance {
            get {
                return ((bool)(this["LeftEntrance"]));
            }
            set {
                this["LeftEntrance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RightEntrance {
            get {
                return ((bool)(this["RightEntrance"]));
            }
            set {
                this["RightEntrance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Traverse {
            get {
                return ((bool)(this["Traverse"]));
            }
            set {
                this["Traverse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HandAuto {
            get {
                return ((bool)(this["HandAuto"]));
            }
            set {
                this["HandAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte EntranceTraverseNumber {
            get {
                return ((byte)(this["EntranceTraverseNumber"]));
            }
            set {
                this["EntranceTraverseNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte ExportTraverseNumber {
            get {
                return ((byte)(this["ExportTraverseNumber"]));
            }
            set {
                this["ExportTraverseNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDrill {
            get {
                return ((bool)(this["AutoDrill"]));
            }
            set {
                this["AutoDrill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public global::GD_STD.Enum.RACK_ROUTE ExportTraverseRoute {
            get {
                return ((global::GD_STD.Enum.RACK_ROUTE)(this["ExportTraverseRoute"]));
            }
            set {
                this["ExportTraverseRoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportTraverseAuto {
            get {
                return ((bool)(this["ExportTraverseAuto"]));
            }
            set {
                this["ExportTraverseAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EntranceTraverseAuto {
            get {
                return ((bool)(this["EntranceTraverseAuto"]));
            }
            set {
                this["EntranceTraverseAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrawLine {
            get {
                return ((bool)(this["DrawLine"]));
            }
            set {
                this["DrawLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MillingCutter {
            get {
                return ((bool)(this["MillingCutter"]));
            }
            set {
                this["MillingCutter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tapping {
            get {
                return ((bool)(this["Tapping"]));
            }
            set {
                this["Tapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public byte ExportTraverseSnsorCount {
            get {
                return ((byte)(this["ExportTraverseSnsorCount"]));
            }
            set {
                this["ExportTraverseSnsorCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public byte ExportTraverseLeftSnsorCount {
            get {
                return ((byte)(this["ExportTraverseLeftSnsorCount"]));
            }
            set {
                this["ExportTraverseLeftSnsorCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte ExportTraverseRightSnsorCount {
            get {
                return ((byte)(this["ExportTraverseRightSnsorCount"]));
            }
            set {
                this["ExportTraverseRightSnsorCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Reverse {
            get {
                return ((bool)(this["Reverse"]));
            }
            set {
                this["Reverse"] = value;
            }
        }
    }
}
