//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSTD105.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Power : global::System.Configuration.ApplicationSettingsBase {
        
        private static Power defaultInstance = ((Power)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Power())));
        
        public static Power Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MiddleAxisX {
            get {
                return ((double)(this["MiddleAxisX"]));
            }
            set {
                this["MiddleAxisX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MiddleAxisY {
            get {
                return ((double)(this["MiddleAxisY"]));
            }
            set {
                this["MiddleAxisY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MiddleAxisZ {
            get {
                return ((double)(this["MiddleAxisZ"]));
            }
            set {
                this["MiddleAxisZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftAxisX {
            get {
                return ((double)(this["LeftAxisX"]));
            }
            set {
                this["LeftAxisX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftAxisY {
            get {
                return ((double)(this["LeftAxisY"]));
            }
            set {
                this["LeftAxisY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LeftAxisZ {
            get {
                return ((double)(this["LeftAxisZ"]));
            }
            set {
                this["LeftAxisZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RightAxisX {
            get {
                return ((double)(this["RightAxisX"]));
            }
            set {
                this["RightAxisX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RightAxisY {
            get {
                return ((double)(this["RightAxisY"]));
            }
            set {
                this["RightAxisY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RightAxisZ {
            get {
                return ((double)(this["RightAxisZ"]));
            }
            set {
                this["RightAxisZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ArmAxisX {
            get {
                return ((double)(this["ArmAxisX"]));
            }
            set {
                this["ArmAxisX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ArmAxisY {
            get {
                return ((double)(this["ArmAxisY"]));
            }
            set {
                this["ArmAxisY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ArmAxisZ {
            get {
                return ((double)(this["ArmAxisZ"]));
            }
            set {
                this["ArmAxisZ"] = value;
            }
        }
    }
}
