//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSTD105.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class MecSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static MecSetting defaultInstance = ((MecSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MecSetting())));
        
        public static MecSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999,9999999,9999999")]
        public string LeftMeasuringPosition {
            get {
                return ((string)(this["LeftMeasuringPosition"]));
            }
            set {
                this["LeftMeasuringPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999,9999999,9999999")]
        public string MiddleMeasuringPosition {
            get {
                return ((string)(this["MiddleMeasuringPosition"]));
            }
            set {
                this["MiddleMeasuringPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999,9999999,9999999")]
        public string RighMeasuringPosition {
            get {
                return ((string)(this["RighMeasuringPosition"]));
            }
            set {
                this["RighMeasuringPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double LeftSensorZero {
            get {
                return ((double)(this["LeftSensorZero"]));
            }
            set {
                this["LeftSensorZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double MiddleSensorZero {
            get {
                return ((double)(this["MiddleSensorZero"]));
            }
            set {
                this["MiddleSensorZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double RighSensorZero {
            get {
                return ((double)(this["RighSensorZero"]));
            }
            set {
                this["RighSensorZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1698.427")]
        public double LeftTotalLength {
            get {
                return ((double)(this["LeftTotalLength"]));
            }
            set {
                this["LeftTotalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1003.772")]
        public double MiddleTotalLength {
            get {
                return ((double)(this["MiddleTotalLength"]));
            }
            set {
                this["MiddleTotalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("549.105")]
        public double RighTotalLength {
            get {
                return ((double)(this["RighTotalLength"]));
            }
            set {
                this["RighTotalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999,9999999,9999999")]
        public string MiddleBorrowMeasuringPosition {
            get {
                return ((string)(this["MiddleBorrowMeasuringPosition"]));
            }
            set {
                this["MiddleBorrowMeasuringPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double MiddleBorrowSensorZero {
            get {
                return ((double)(this["MiddleBorrowSensorZero"]));
            }
            set {
                this["MiddleBorrowSensorZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("141.72")]
        public double MiddleHighSensorZ {
            get {
                return ((double)(this["MiddleHighSensorZ"]));
            }
            set {
                this["MiddleHighSensorZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double HandMaterialCorrectionWorkRange {
            get {
                return ((double)(this["HandMaterialCorrectionWorkRange"]));
            }
            set {
                this["HandMaterialCorrectionWorkRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double HandMaterialZeroToWorkRange {
            get {
                return ((double)(this["HandMaterialZeroToWorkRange"]));
            }
            set {
                this["HandMaterialZeroToWorkRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double HandJobLimit {
            get {
                return ((double)(this["HandJobLimit"]));
            }
            set {
                this["HandJobLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double HandOutClampToZeroLength {
            get {
                return ((double)(this["HandOutClampToZeroLength"]));
            }
            set {
                this["HandOutClampToZeroLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("513.08")]
        public double ClampDownEntranceL {
            get {
                return ((double)(this["ClampDownEntranceL"]));
            }
            set {
                this["ClampDownEntranceL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("515.08")]
        public double ClampDownExportL {
            get {
                return ((double)(this["ClampDownExportL"]));
            }
            set {
                this["ClampDownExportL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("518.04")]
        public double ClampDownEntranceR {
            get {
                return ((double)(this["ClampDownEntranceR"]));
            }
            set {
                this["ClampDownEntranceR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("514.92")]
        public double ClampDownExportR {
            get {
                return ((double)(this["ClampDownExportR"]));
            }
            set {
                this["ClampDownExportR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1083.35")]
        public double SideClampEntranceL {
            get {
                return ((double)(this["SideClampEntranceL"]));
            }
            set {
                this["SideClampEntranceL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1083.4")]
        public double SideClampExportL {
            get {
                return ((double)(this["SideClampExportL"]));
            }
            set {
                this["SideClampExportL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(290.05,312.99,194.15,319.45)(290.05,219.88,194.38,321.5)(290.0,125.32,194.38,321" +
            ".2)(290.0,26.94,194.50,318.15)")]
        public string LeftEntranceDrillSetting {
            get {
                return ((string)(this["LeftEntranceDrillSetting"]));
            }
            set {
                this["LeftEntranceDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(10.17,312.37,194.76,318.28)(9.72,219.04,194.76,317.28)(9.80,122.41,194.76,318.45" +
            ")(9.72,28.90,194.76,317.14)")]
        public string LeftExportDrillSetting {
            get {
                return ((string)(this["LeftExportDrillSetting"]));
            }
            set {
                this["LeftExportDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(308.158,150,113.95,7.88)(227.705,150,113.95,7.07)(147.535,150,113.95,7.71)(66.78" +
            "9,150,113.95,7.44)(-12.521,150,113.95,7.71)")]
        public string MiddleDrillSetting {
            get {
                return ((string)(this["MiddleDrillSetting"]));
            }
            set {
                this["MiddleDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(289.86,312.57,127.76,269.80)(289.23,220.63,128.22,267.70)(289.45,123.23,128.22,2" +
            "69.40)(288.83,29.97,128.69,268.30)")]
        public string RightEntranceDrillSetting {
            get {
                return ((string)(this["RightEntranceDrillSetting"]));
            }
            set {
                this["RightEntranceDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(10.54,312.68,128.46,268.7)(10.20,218.67,128.46,270.00)(10.39,123.55,128.46,269.5" +
            "0)(10.06,29.70,128.46,270.50)")]
        public string RightExportDrillSetting {
            get {
                return ((string)(this["RightExportDrillSetting"]));
            }
            set {
                this["RightExportDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HMI {
            get {
                return ((bool)(this["HMI"]));
            }
            set {
                this["HMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GUANDA")]
        public string Company {
            get {
                return ((string)(this["Company"]));
            }
            set {
                this["Company"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double ClampDownThickness {
            get {
                return ((double)(this["ClampDownThickness"]));
            }
            set {
                this["ClampDownThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte HandSpeed {
            get {
                return ((byte)(this["HandSpeed"]));
            }
            set {
                this["HandSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrillWarehouse {
            get {
                return ((bool)(this["DrillWarehouse"]));
            }
            set {
                this["DrillWarehouse"] = value;
            }
        }
    }
}
