//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSTD105.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class MecSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static MecSetting defaultInstance = ((MecSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MecSetting())));
        
        public static MecSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50,514.2,530.51")]
        public string LeftMeasuringPosition {
            get {
                return ((string)(this["LeftMeasuringPosition"]));
            }
            set {
                this["LeftMeasuringPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50,350,413.23")]
        public string MiddleMeasuringPosition {
            get {
                return ((string)(this["MiddleMeasuringPosition"]));
            }
            set {
                this["MiddleMeasuringPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50,511.22,431.69")]
        public string RighMeasuringPosition {
            get {
                return ((string)(this["RighMeasuringPosition"]));
            }
            set {
                this["RighMeasuringPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1698.427")]
        public double LeftTotalLength {
            get {
                return ((double)(this["LeftTotalLength"]));
            }
            set {
                this["LeftTotalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1003.772")]
        public double MiddleTotalLength {
            get {
                return ((double)(this["MiddleTotalLength"]));
            }
            set {
                this["MiddleTotalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("549.105")]
        public double RighTotalLength {
            get {
                return ((double)(this["RighTotalLength"]));
            }
            set {
                this["RighTotalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double HandMaterialCorrectionWorkRange {
            get {
                return ((double)(this["HandMaterialCorrectionWorkRange"]));
            }
            set {
                this["HandMaterialCorrectionWorkRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1248")]
        public double HandMaterialZeroToWorkRange {
            get {
                return ((double)(this["HandMaterialZeroToWorkRange"]));
            }
            set {
                this["HandMaterialZeroToWorkRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9140")]
        public double HandJobLimit {
            get {
                return ((double)(this["HandJobLimit"]));
            }
            set {
                this["HandJobLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public double HandOutClampToZeroLength {
            get {
                return ((double)(this["HandOutClampToZeroLength"]));
            }
            set {
                this["HandOutClampToZeroLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("519.46")]
        public double ClampDownEntranceL {
            get {
                return ((double)(this["ClampDownEntranceL"]));
            }
            set {
                this["ClampDownEntranceL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("519.3")]
        public double ClampDownExportL {
            get {
                return ((double)(this["ClampDownExportL"]));
            }
            set {
                this["ClampDownExportL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("520.82")]
        public double ClampDownEntranceR {
            get {
                return ((double)(this["ClampDownEntranceR"]));
            }
            set {
                this["ClampDownEntranceR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("517.46")]
        public double ClampDownExportR {
            get {
                return ((double)(this["ClampDownExportR"]));
            }
            set {
                this["ClampDownExportR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1083.35")]
        public double SideClampEntranceL {
            get {
                return ((double)(this["SideClampEntranceL"]));
            }
            set {
                this["SideClampEntranceL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1083.4")]
        public double SideClampExportL {
            get {
                return ((double)(this["SideClampExportL"]));
            }
            set {
                this["SideClampExportL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(290.1,312.99,192.65,319.8)(290.1,219.88,192.88,321.8)(290.1,125.32,192.88,321.8)" +
            "(290.1,26.94,193,318.75)")]
        public string LeftEntranceDrillSetting {
            get {
                return ((string)(this["LeftEntranceDrillSetting"]));
            }
            set {
                this["LeftEntranceDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(9.05,312.37,191.68,320.3)(9.35,219.04,191.68,319.1)(9.05,122.41,191.68,320.4)(9." +
            "05,28.9,191.68,319.4)")]
        public string LeftExportDrillSetting {
            get {
                return ((string)(this["LeftExportDrillSetting"]));
            }
            set {
                this["LeftExportDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(307.87,150,112.26,-115.4)(227.7,150,112.65,-115.66)(147.57,150,112.65,-115.57)(6" +
            "6.72,150,112.4,-116.36)(-12.5,150,112.4,-115.92)")]
        public string MiddleDrillSetting {
            get {
                return ((string)(this["MiddleDrillSetting"]));
            }
            set {
                this["MiddleDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(289.86,312.57,126.26,269.7)(289.23,220.63,126.72,267.6)(289.45,123.23,126.72,269" +
            ".9)(288.83,29.97,127.19,268)")]
        public string RightEntranceDrillSetting {
            get {
                return ((string)(this["RightEntranceDrillSetting"]));
            }
            set {
                this["RightEntranceDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(10.54,312.68,126.96,268.8)(10.2,218.67,126.96,269.7)(10.39,123.55,126.96,269.7)(" +
            "10.06,29.7,126.96,270.6)")]
        public string RightExportDrillSetting {
            get {
                return ((string)(this["RightExportDrillSetting"]));
            }
            set {
                this["RightExportDrillSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HMI {
            get {
                return ((bool)(this["HMI"]));
            }
            set {
                this["HMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GUANDA")]
        public string Company {
            get {
                return ((string)(this["Company"]));
            }
            set {
                this["Company"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999")]
        public double ClampDownThickness {
            get {
                return ((double)(this["ClampDownThickness"]));
            }
            set {
                this["ClampDownThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short HandSpeed {
            get {
                return ((short)(this["HandSpeed"]));
            }
            set {
                this["HandSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GD_STD.DrillWarehouse DrillWarehouse {
            get {
                return ((global::GD_STD.DrillWarehouse)(this["DrillWarehouse"]));
            }
            set {
                this["DrillWarehouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Deserialize {
            get {
                return ((bool)(this["Deserialize"]));
            }
            set {
                this["Deserialize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("615.2")]
        public double InTotalLength {
            get {
                return ((double)(this["InTotalLength"]));
            }
            set {
                this["InTotalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("576")]
        public double OutTotalLength {
            get {
                return ((double)(this["OutTotalLength"]));
            }
            set {
                this["OutTotalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2290")]
        public double Length {
            get {
                return ((double)(this["Length"]));
            }
            set {
                this["Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2250")]
        public double VerticalToOriginLength {
            get {
                return ((double)(this["VerticalToOriginLength"]));
            }
            set {
                this["VerticalToOriginLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800")]
        public double ArmInDownWingSensorToForntLength {
            get {
                return ((double)(this["ArmInDownWingSensorToForntLength"]));
            }
            set {
                this["ArmInDownWingSensorToForntLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double ArmInDownCheckPosition {
            get {
                return ((double)(this["ArmInDownCheckPosition"]));
            }
            set {
                this["ArmInDownCheckPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9292")]
        public double ArmXToOriginPoint {
            get {
                return ((double)(this["ArmXToOriginPoint"]));
            }
            set {
                this["ArmXToOriginPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("830")]
        public double ArmInTouchOriginLength {
            get {
                return ((double)(this["ArmInTouchOriginLength"]));
            }
            set {
                this["ArmInTouchOriginLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10328")]
        public double VerticalGrippingXLimit {
            get {
                return ((double)(this["VerticalGrippingXLimit"]));
            }
            set {
                this["VerticalGrippingXLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double SafeTouchLength {
            get {
                return ((double)(this["SafeTouchLength"]));
            }
            set {
                this["SafeTouchLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1100")]
        public double EntranceVehicle_Length {
            get {
                return ((double)(this["EntranceVehicle_Length"]));
            }
            set {
                this["EntranceVehicle_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double EntranceVehicle_Raised_Length {
            get {
                return ((double)(this["EntranceVehicle_Raised_Length"]));
            }
            set {
                this["EntranceVehicle_Raised_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double EntranceVehicle_Origin_To_Location_Point_Length {
            get {
                return ((double)(this["EntranceVehicle_Origin_To_Location_Point_Length"]));
            }
            set {
                this["EntranceVehicle_Origin_To_Location_Point_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2355")]
        public double EntranceTraverse_Sort_Total_Length {
            get {
                return ((double)(this["EntranceTraverse_Sort_Total_Length"]));
            }
            set {
                this["EntranceTraverse_Sort_Total_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3530")]
        public double EntranceIn_Traverse_Limit_Total_Length {
            get {
                return ((double)(this["EntranceIn_Traverse_Limit_Total_Length"]));
            }
            set {
                this["EntranceIn_Traverse_Limit_Total_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double EntranceSort_Traverse_Correction {
            get {
                return ((double)(this["EntranceSort_Traverse_Correction"]));
            }
            set {
                this["EntranceSort_Traverse_Correction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-20")]
        public double EntranceTo_ArmSide_Traverse_Correction {
            get {
                return ((double)(this["EntranceTo_ArmSide_Traverse_Correction"]));
            }
            set {
                this["EntranceTo_ArmSide_Traverse_Correction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double EntranceTraverseResolution {
            get {
                return ((double)(this["EntranceTraverseResolution"]));
            }
            set {
                this["EntranceTraverseResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double ExportTraverseResolution {
            get {
                return ((double)(this["ExportTraverseResolution"]));
            }
            set {
                this["ExportTraverseResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExportVehicle_Length {
            get {
                return ((double)(this["ExportVehicle_Length"]));
            }
            set {
                this["ExportVehicle_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExportVehicle_Raised_Length {
            get {
                return ((double)(this["ExportVehicle_Raised_Length"]));
            }
            set {
                this["ExportVehicle_Raised_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExportVehicle_Origin_To_Location_Point_Length {
            get {
                return ((double)(this["ExportVehicle_Origin_To_Location_Point_Length"]));
            }
            set {
                this["ExportVehicle_Origin_To_Location_Point_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExportIn_Traverse_Limit_Total_Length {
            get {
                return ((double)(this["ExportIn_Traverse_Limit_Total_Length"]));
            }
            set {
                this["ExportIn_Traverse_Limit_Total_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExportSort_Traverse_Correction {
            get {
                return ((double)(this["ExportSort_Traverse_Correction"]));
            }
            set {
                this["ExportSort_Traverse_Correction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExportTo_ArmSide_Traverse_Correction {
            get {
                return ((double)(this["ExportTo_ArmSide_Traverse_Correction"]));
            }
            set {
                this["ExportTo_ArmSide_Traverse_Correction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public short MiddleAxisTorque {
            get {
                return ((short)(this["MiddleAxisTorque"]));
            }
            set {
                this["MiddleAxisTorque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public short RighAxisTorque {
            get {
                return ((short)(this["RighAxisTorque"]));
            }
            set {
                this["RighAxisTorque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public short LeftAxisTorque {
            get {
                return ((short)(this["LeftAxisTorque"]));
            }
            set {
                this["LeftAxisTorque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double ThroughLength {
            get {
                return ((double)(this["ThroughLength"]));
            }
            set {
                this["ThroughLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double RankStratLength {
            get {
                return ((double)(this["RankStratLength"]));
            }
            set {
                this["RankStratLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double RankEndLength {
            get {
                return ((double)(this["RankEndLength"]));
            }
            set {
                this["RankEndLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double TouchMUL {
            get {
                return ((double)(this["TouchMUL"]));
            }
            set {
                this["TouchMUL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double EndMUL {
            get {
                return ((double)(this["EndMUL"]));
            }
            set {
                this["EndMUL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double AllowDrillTolerance {
            get {
                return ((double)(this["AllowDrillTolerance"]));
            }
            set {
                this["AllowDrillTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double ArmInDownBellySensorToForntLength {
            get {
                return ((double)(this["ArmInDownBellySensorToForntLength"]));
            }
            set {
                this["ArmInDownBellySensorToForntLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double ArmFeedOriginToOutUpRoll {
            get {
                return ((double)(this["ArmFeedOriginToOutUpRoll"]));
            }
            set {
                this["ArmFeedOriginToOutUpRoll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double WingSensorHigh {
            get {
                return ((double)(this["WingSensorHigh"]));
            }
            set {
                this["WingSensorHigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double BellySensorHigh {
            get {
                return ((double)(this["BellySensorHigh"]));
            }
            set {
                this["BellySensorHigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double Entrance_SafetyGap {
            get {
                return ((double)(this["Entrance_SafetyGap"]));
            }
            set {
                this["Entrance_SafetyGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExportTraverse_Sort_Total_Length {
            get {
                return ((double)(this["ExportTraverse_Sort_Total_Length"]));
            }
            set {
                this["ExportTraverse_Sort_Total_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100")]
        public string ConveyorPosition {
            get {
                return ((string)(this["ConveyorPosition"]));
            }
            set {
                this["ConveyorPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170")]
        public double HandSlowToOriginLength {
            get {
                return ((double)(this["HandSlowToOriginLength"]));
            }
            set {
                this["HandSlowToOriginLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double DrillProtectionX {
            get {
                return ((double)(this["DrillProtectionX"]));
            }
            set {
                this["DrillProtectionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double DrillProtectionLRY {
            get {
                return ((double)(this["DrillProtectionLRY"]));
            }
            set {
                this["DrillProtectionLRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double DrillProtectionMY {
            get {
                return ((double)(this["DrillProtectionMY"]));
            }
            set {
                this["DrillProtectionMY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double OtherProtectionX {
            get {
                return ((double)(this["OtherProtectionX"]));
            }
            set {
                this["OtherProtectionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double OtherProtectionLRY {
            get {
                return ((double)(this["OtherProtectionLRY"]));
            }
            set {
                this["OtherProtectionLRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double OtherProtectionMY {
            get {
                return ((double)(this["OtherProtectionMY"]));
            }
            set {
                this["OtherProtectionMY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double StrWidth {
            get {
                return ((double)(this["StrWidth"]));
            }
            set {
                this["StrWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("520")]
        public double LeftYAxisLimit {
            get {
                return ((double)(this["LeftYAxisLimit"]));
            }
            set {
                this["LeftYAxisLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("520")]
        public double RightYAxisLimit {
            get {
                return ((double)(this["RightYAxisLimit"]));
            }
            set {
                this["RightYAxisLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double MiddleYAxisLimit {
            get {
                return ((double)(this["MiddleYAxisLimit"]));
            }
            set {
                this["MiddleYAxisLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double LeftOriginToSideLength {
            get {
                return ((double)(this["LeftOriginToSideLength"]));
            }
            set {
                this["LeftOriginToSideLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double RightOriginToSideLength {
            get {
                return ((double)(this["RightOriginToSideLength"]));
            }
            set {
                this["RightOriginToSideLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double MiddleOriginToSideLength {
            get {
                return ((double)(this["MiddleOriginToSideLength"]));
            }
            set {
                this["MiddleOriginToSideLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HandXLimit {
            get {
                return ((string)(this["HandXLimit"]));
            }
            set {
                this["HandXLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HandArmInZSafeLength {
            get {
                return ((string)(this["HandArmInZSafeLength"]));
            }
            set {
                this["HandArmInZSafeLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Hand {
            get {
                return ((string)(this["Hand"]));
            }
            set {
                this["Hand"] = value;
            }
        }
    }
}
